#!/usr/bin/env node
// serve.mjs - zero-dep localhost static server for the dashboard.
// Needed because index.html fetches ./data.json, which browsers block on file://.
// Serves ONLY files inside this dashboard/ directory. Localhost only, no writes.
//   npm run dashboard   (or: node dashboard/serve.mjs [port])
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize, sep, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.argv[2] ?? process.env.DASHBOARD_PORT ?? 4173);
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
};

createServer(async (req, res) => {
  const urlPath = decodeURIComponent(new URL(req.url, 'http://x').pathname);
  const rel = urlPath === '/' ? 'index.html' : urlPath.slice(1);
  const file = normalize(join(DIR, rel));
  if (!file.startsWith(DIR + sep) && file !== join(DIR, 'index.html')) {
    res.writeHead(403); return res.end('forbidden');
  }
  try {
    const body = await readFile(file);
    res.writeHead(200, {
      'Content-Type': MIME[extname(file)] ?? 'application/octet-stream',
      'Cache-Control': 'no-store', // data.json is regenerated by report runs
    });
    res.end(body);
  } catch {
    res.writeHead(404); res.end('not found');
  }
}).listen(PORT, '127.0.0.1', () => {
  console.log(`Dashboard: http://127.0.0.1:${PORT}/ (Ctrl-C to stop)`);
});
